baseURL = 'https://honeybearfolio.github.io/'
languageCode = 'en-us'
title = 'HoneyBear Folio'
theme = 'honeybear'

[[module.imports]]
  path = "github.com/honeybearfolio/docs"
  [[module.imports.mounts]]
    source = "content"
    target = "content/docs"

[params]
  description = "A privacy-focused, local-first personal finance desktop application"
  author = "HoneyBearFolio"
  github = "https://github.com/honeybearfolio/HoneyBear-Folio"
  license = "AGPL-3.0"
  version = "0.4.0"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = 'monokai'
    lineNos = false
    codeFences = true

[menu]
  [[menu.main]]
    name = "Features"
    url = "/#features"
    weight = 1
  [[menu.main]]
    name = "Screenshots"
    url = "/#screenshots"
    weight = 2
  [[menu.main]]
    name = "Download"
    url = "/#download"
    weight = 3
  [[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 4
  [[menu.main]]
    name = "GitHub"
    url = "https://github.com/honeybearfolio/HoneyBear-Folio"
    weight = 5
